config/routes.rb
CrmApp::Application.routes.draw do
  
  resources :companies do
	resources :individuals 
  end
  
  get "companies/index"

  
  root :to => 'companies#index'

end

app/models/company.rb
class Company < ActiveRecord::Base

	has_many :individuals

	validates :companyName, :customerType, :industry, :presence => true
	validates :companyName, :uniqueness => true
	
	COMPANY_TYPES = ["Parent", "Child", "Sole"]
	CUSTOMER_TYPES = ["Partner", "Competitor", "Former Customer", "Vendor", "Reseller"]
	INDUSTRY_TYPES = ["Software", "Manufacturing", "Finance", "Healthcare", "Others"]
	VIP_TYPES = ["Low", "Medium", "High"]
end

app/models/individual.rb
class Individual < ActiveRecord::Base
    
	belongs_to :company
	validates :firstName, :lastName, :department, :position, :contactType, :presence => true
	
	DEPARTMENT_TYPES = ["Admin", "IT", "Finance", "Development", "QA", "Others"]
	POSITION_TYPES  = ["CEO", "VP", "CFO", "Developer", "HR", "Others"]
    CONTACT_TYPES = ["Primary", "Secondary", "Regular"]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  # GET /companies
  # GET /companies.xml
  def index
    @companies = Company.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.xml
  def show
    @company = Company.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.xml
  def new
    @company = Company.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  # POST /companies.xml
  def create
    @company = Company.new(params[:company])

    respond_to do |format|
      if @company.save
        format.html { redirect_to(@company, :notice => 'Company was successfully created.') }
        format.xml  { render :xml => @company, :status => :created, :location => @company }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @company.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.xml
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to(@company, :notice => 'Company was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @company.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.xml
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to(companies_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/emailer_controller.rb
class EmailerController < ApplicationController
   def index
      render :file => 'app\views\notifier\contact_email.text.erb'
   end

   def sendmail
      email = @params["email"]
	  recipient = email["recipient"]
	  subject = email["subject"]
	  message = email["message"]
      Emailer.deliver_contact(recipient, subject, message)
      return if request.xhr?
      render :text => 'Message sent successfully'
   end

end

app/controllers/individuals_controller.rb
class IndividualsController < ApplicationController
  # GET /individuals
  # GET /individuals.xml
  before_filter :load_company
  
  def index
    @individuals = Individual.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @individuals }
    end
  end

  # GET /individuals/1
  # GET /individuals/1.xml
  def show
    @individual = Individual.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @individual }
    end
  end

  # GET /individuals/new
  # GET /individuals/new.xml
  def new
    @individual = Individual.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @individual }
    end
  end

  # GET /individuals/1/edit
  def edit
    #@individual = Individual.find(params[:id])
	@individual = @company.individuals.find(params[:id])
  end

  # POST /individuals
  # POST /individuals.xml
  def create
   #@individual = Individual.new(params[:individual])
   @individual = @company.individuals.new(params[:individual])
   if @individual.save
	redirect_to @company, :notice => "Individual successfully added."
   else
	redirect_to @company, :notice => "Unable to add individual."
   end

   # respond_to do |format|
   #   if @individual.save
   #     format.html { redirect_to(@individual, :notice => 'Individual was successfully created.') }
   #     format.xml  { render :xml => @individual, :status => :created, :location => @individual }
   #   else
   #     format.html { render :action => "new" }
   #     format.xml  { render :xml => @individual.errors, :status => :unprocessable_entity }
   #   end
   # end
  end

  # PUT /individuals/1
  # PUT /individuals/1.xml
  def update
    #@individual = Individual.find(params[:id])
	@individual = @company.individuals.new(params[:individual])
	
	
	#@individual = @company.individuals.find(params[:id])

   #if @individual.save
	#redirect_to @company, :notice => "Individual successfully added."
   #else
	#redirect_to @company, :notice => "Unable to add individual."
  # end
	
    respond_to do |format|
      if @individual.update_attributes(params[:individual])
        format.html { redirect_to(@individual, :notice => 'Individual was successfully updated.') }
        format.xml  { head :ok }
      else
       format.html { render :action => "edit" }
        format.xml  { render :xml => @individual.errors, :status => :unprocessable_entity }
     end
    end
  end

  # DELETE /individuals/1
  # DELETE /individuals/1.xml
  def destroy
    #@individual = Individual.find(params[:id])
	@individual = @company.individuals.find(params[:id])
    @individual.destroy
	redirect_to @company, :notice => "Individual deleted."

    #respond_to do |format|
    #  format.html { redirect_to(individuals_url) }
    #  format.xml  { head :ok }
   # end
  end
  
  private
	def load_company
		@company = Company.find(params[:company_id])
	end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/emailer_helper.rb
module EmailerHelper
end

app/helpers/individuals_helper.rb
module IndividualsHelper
end

app/views/companies/_company.html.erb
<%= div_for company do %> 
 <h3>
	<%= link_to company.companyname, company %>
	<span class='actions'>
		<%= link_to "Edit", edit_company_path(company) %>
		<%= link_to "Delete", company, :confirm => "Are you sure?", 
			:method => :delete %>
	</span>
 </h3>  
<%= company.body %>
<% end %>

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= label_tag  'Company Name' %><br />
    <%= f.text_field :companyName, :size => 60 %>
  </div>
  <div class="field">
    <%= label_tag  'Company Type' %><br />
    <%= f.select :companyType, Company::COMPANY_TYPES,
		:prompt => 'Choose a value' %>
  </div>
  <div class="field">
    <%= label_tag  'Customer Type' %><br />
    <%= f.select :customerType, Company::CUSTOMER_TYPES,
		:prompt => 'Choose a value' %>
  </div>
  <div class="field">
    <%= label_tag  'Industry' %><br />
    <%= f.select :industry, Company::INDUSTRY_TYPES,
		:prompt => 'Choose a value' %>
  </div>
  <div class="field">
    <%= label_tag  'TIN No.' %><br />
    <%= f.text_field :tinNo, :size => 12 %>
  </div>
  <div class="field">
    <%= label_tag  'VIP' %><br />
    <%= f.select :vip, Company::VIP_TYPES,
		:prompt => 'Choose a value' %>
  </div>
  <div class="field">
    <%= label_tag  'Description' %><br />
    <%= f.text_area :description, :rows => 6, :cols => 50 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<div id="company_list">
<h1>Company Summary</h1>

<table>
<tr>
	<b><td>Company</td>
	<td>Company Type</td>
	<td>Customer Type</td>
	<td>Industry</td>
	<td>TIN</td>
</tr>

<% @companies.each do |company| %>
  <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
  
    <td>
		<!-- <p><%= company.companyName %></p> orig -->
		<%= link_to company.companyName, company %>
	</td>
    <td>
		<%= link_to company.companyType, company %>
	</td>
	<td>
		<%= link_to company.customerType, company %>
	</td>
	<td>
		<%= link_to company.industry, company %>
	</td>
	<td>
		<%= link_to company.tinNo, company %>
	</td>
		
    <td class = "list_actions">
		<!-- <%= link_to 'Show ', company %> -->
		<%= link_to 'Edit ', edit_company_path(company) %>
		<%= link_to 'Destroy', company, :confirm => 'Are you sure?', :method => :delete %>
	</td>
  </tr>
<% end %>
</table>
</div>

<br />

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<% if notice %>
	<p id="notice"><%= notice %></p>
<% end %>

<p>
  <b>Companyname:</b>
  <%= @company.companyName %>
</p>
<p>
  <b>Companytype:</b>
  <%= @company.companyType %>
</p>

<p>
  <b>Customertype:</b>
  <%= @company.customerType %>
</p>

<p>
  <b>Industry:</b>
  <%= @company.industry %>
</p>

<p>
  <b>Tinno:</b>
  <%= @company.tinNo %>
</p>

<p>
  <b>Vip:</b>
  <%= @company.vip %>
</p>

<p>
  <b>Description:</b>
  <%= @company.description %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

<h3>Individual</h3>
<div id="individual">
	<%= render @company.individuals %>
</div>
<%= render :file => 'individuals/new' %>

app/views/individuals/_form.html.erb
<%= form_for (@individual) do |f| %>
  <% if @individual.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@individual.errors.count, "error") %> prohibited this individual from being saved:</h2>

      <ul>
      <% @individual.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
    <%= label_tag  'Salutation' %><br />
    <%= f.text_field :salutation %>
  </div>
  <div class="field">
    <%= label_tag  'Firstname' %><br />
    <%= f.text_field :firstName %>
  </div>
  <div class="field">
    <%= label_tag 'Middlename' %><br />
    <%= f.text_field :middleName %>
  </div>
  <div class="field">
    <%= label_tag  'Lastname' %><br />
    <%= f.text_field :lastName %>
  </div>
  <div class="field">
    <%= label_tag  'suffix' %><br />
    <%= f.text_field :suffix %>
  </div>
  
  <div class="field">
    <%= label_tag  'Department' %><br />
	<%= f.select :department, Individual::DEPARTMENT_TYPES,
		:prompt => 'Choose a value' %>
  </div>
  <div class="field">
    <%= label_tag  'Position' %><br />
    <%= f.select :position, Individual::POSITION_TYPES,
		:prompt => 'Choose a value' %>
  </div>
  <div class="field">
    <%= label_tag  'Other Position Description' %><br />
    <%= f.text_field :positionDesc %>
  </div>
  <div class="field">
    <%= label_tag  'Contact Type' %><br />
        <%= f.select :contactType, Individual::CONTACT_TYPES,
		:prompt => 'Choose a value' %>
  </div>
  <div class="field">
    <%= label_tag  'Description' %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :company_id %><br />
    <%= f.text_field :company_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/individuals/_individual.html.erb
<%= div_for individual do %>  
	<h3>    
	
    <%= individual.firstName %> <%= individual.lastName %> 
		<span class='actions'>    
		    <!-- <%= link_to "Edit", company_individual_path(:company_id => @company, 
					:id => individual) %> -->
			<%= link_to 'Delete', company_individual_path(:company_id => @company, 
			:id => individual), :confirm => 'Are you sure?', :method => :delete %>    
		</span>
	</h3>

	<% end %> 

app/views/individuals/_notify_friend.html.erb
<%= form_tag(notify_friend_individual_path(@individual), :id => 'notify_friend_form', 
:style => 'display:none') do %>

<div class="field">
	<%= label_tag :name, 'Your name' %><br />
	<%= text_field_tag :name %>
</div>
<div class="field">
	<%= label_tag :email, 'Email Address' %><br />
	<%= text_field_tag :email %>
</div>
<div class="actions">
	<%= submit_tag 'Send' %> or 
	<%= link_to 'Cancel', '#',:onclick => "$('notify_friend_form').slideup()" %>
</div>

<% end %>

app/views/individuals/edit.html.erb
<h1>Editing individual</h1>

<%= render 'form' %>

app/views/individuals/index.html.erb
<div id="company_list">
<h1>Individual Summary</h1>

<table>
  <tr>
    <th>Salutation</th>
    <th>Firstname</th>
    <th>Middlename</th>
    <th>Lastname</th>
    <th>Suffix</th>
    <th>Department</th>
    <th>Position</th>
    <th>Contact Type</th>
    <th>Company</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @individuals.each do |individual| %>
  <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
    <td>
		<p><%= individual.salutation %></p>
	</td>
	<td>
		<p><%= individual.firstName %></p>
	</td>
	<td>
		<p><%= individual.middleName %></p>
	</td>
	<td>
		<p><%= individual.lastName %></p>
	</td>
	<td>
		<p><%= individual.suffix %></p>
	</td>
	<td>
		<p><%= individual.department %></p>
	</td>
	<td>
		<p><%= individual.position %></p>
	</td>
	<td>
		<p><%= individual.contactType %></p>
	</td>
	<td>
		<p><%= individual.company_id %></p>
	</td>
	<td class = "list_actions">
		<%= link_to 'Show', individual %>
		<%= link_to 'Edit', edit_individual_path(individual) %>
		<%= link_to 'Destroy', individual, :confirm => 'Are you sure?', :method => :delete %>
		
	</td>
  </tr>
<% end %>
</table>
</div>

<br />

<%= link_to 'New Individual', new_individual_path %>

app/views/individuals/new.html.erb
<%= form_for([@company, @company.individuals.new]) do |f| %>  
  <div class="field">
    <%= label_tag  'Salutation' %><br />
    <%= f.text_field :salutation %>
  </div>
  <div class="field">
    <%= label_tag  'Firstname' %><br />
    <%= f.text_field :firstName %>
  </div>
  <div class="field">
    <%= label_tag 'Middlename' %><br />
    <%= f.text_field :middleName %>
  </div>
  <div class="field">
    <%= label_tag  'Lastname' %><br />
    <%= f.text_field :lastName %>
  </div>
  <div class="field">
    <%= label_tag  'suffix' %><br />
    <%= f.text_field :suffix %>
  </div>
  
  <div class="field">
    <%= label_tag  'Department' %><br />
	<%= f.select :department, Individual::DEPARTMENT_TYPES,
		:prompt => 'Choose a value' %>
  </div>
  <div class="field">
    <%= label_tag  'Position' %><br />
    <%= f.select :position, Individual::POSITION_TYPES,
		:prompt => 'Choose a value' %>
  </div>
  <div class="field">
    <%= label_tag  'Other Position Description' %><br />
    <%= f.text_field :positionDesc %>
  </div>
  <div class="field">
    <%= label_tag  'Contact Type' %><br />
        <%= f.select :contactType, Individual::CONTACT_TYPES,
		:prompt => 'Choose a value' %>
  </div>
  <div class="field">
    <%= label_tag  'Description' %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :company_id %><br />
    <%= f.text_field :company_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/individuals/new.js.erb
$("<%= escape_javascript 
render(:file => 'individuals/new.html.erb') %>").insertAfter('#individuals');
$('#new_individual').slideDown();
$('#new_individual_link').hide();

app/views/individuals/show.html.erb
<% if notice %>
	<p id="notice"><%= notice %></p>
<% end %>


<p>
  <b>Salutation:</b>
  <%= @individual.salutation %>
</p>

<p>
  <b>Firstname:</b>
  <%= @individual.firstName %>
</p>

<p>
  <b>Middlename:</b>
  <%= @individual.middleName %>
</p>

<p>
  <b>Lastname:</b>
  <%= @individual.lastName %>
</p>

<p>
  <b>Suffix:</b>
  <%= @individual.suffix %>
</p>

<p>
  <b>Department:</b>
  <%= @individual.department %>
</p>

<p>
  <b>Position:</b>
  <%= @individual.position %>
</p>

<p>
  <b>Positiondesc:</b>
  <%= @individual.positionDesc %>
</p>

<p>
  <b>Contacttype:</b>
  <%= @individual.contactType %>
</p>

<p>
  <b>Description:</b>
  <%= @individual.description %>
</p>

<p>
  <b>Company:</b>
  <%= @individual.company_id %>
</p>


<%= link_to 'Edit', edit_individual_path(@individual) %> |
<%= link_to 'Back', individuals_path %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CRM Application</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag 'jquery-1.4.2.min', 'rails', 'application' %>
  <%= csrf_meta_tag %>
</head>
<body id="company">
  <div id="banner">
   <!-- <%= image_tag("logo.png") %> -->
    <%= @page_title || "Unicorn Technology CRM Application" %>
  </div>
  <div id="columns">
    <div id="side">
      <!-- START:hidden_div -->
      <% if @cart %>
        <%= hidden_div_if(@cart.line_items.empty?, :id => "cart") do %>
          <%= render @cart %>
        <% end %>
      <% end %>
    <!-- END:hidden_div -->

	  <%= link_to "Company", :controller => "companies", :action => "index" %><br />

    </div>
    <div id="main">
      <%= yield %>
    </div>
  </div>
  
  <%= content_tag :p, notice, :class => 'notice' if notice.present? %>
  <%= content_tag :p, alert, :class => 'alert' if alert.present? %>
  
</body>
</html>

app/views/notifier/contact_email.text.erb
Notifier#contact_email

<%= @greeting %>, find me in app/views/app/views/notifier/contact_email.text.erb

app/views/notifier/general_email.text.erb
Notifier#general_email

<%= @greeting %>, find me in app/views/app/views/notifier/general_email.text.erb